### ISSUE TITLE
Train/Test Set

### ISSUE THREAD

**Issue by philhoonoh** [AI21Labs/Parallel-Context-Windows#11]
Thanks for the PCW implementation!

In the README.md, it states:

> `Due to the fact that the paper's results were based on an earlier implementation of PCW and not [HuggingFace Transformers](https://huggingface.co/docs/transformers/index), the results produced using this code may differ slightly from those shown in the paper.`

So I was wondering whether the train sample and test sample in the paper are the same as those in this repository. 

Thanks in advance!

**Comment by nirrai21** [comment]
Hi, they should be since we used the same random seed in both implementations. In case you use a different numpy/pandas version however it might not be identical since the random seed behaviour depends on their versions.

**Comment by philhoonoh** [comment]
Thank you for the reply!
