### ISSUE TITLE
Bloom support?

### ISSUE THREAD

**Issue by ScottishFold007** [AI21Labs/Parallel-Context-Windows#4]
Is it possible to support a model like bloom based on alibi attention mechanism?

**Comment by nirrai21** [comment]
Hi,
Though we didn't implement PCW on bloom it should be relatively straight forward. Unfortunately, we do not plan to add this support in the near future. In case you wish to contribute to this repo - we will be more than happy to review your code and provide support to any efforts to add support to bloom models.
Note that we have just added support to LLaMa models, so make sure to check out the new code as well.
