### ISSUE TITLE
QA datasets instances

### ISSUE THREAD

**Issue by salvatoreferragamo** [AI21Labs/Parallel-Context-Windows#6]
Can you give some assists in  QA datasets, as all the functions in Dataloader are related to classification tasks, as well as the evaluation..
What's your specific processing when it comes to the HotpotQA or Natural Questions ?

**Comment by nirrai21** [comment]
It depends on the use case in question: 
- If you wish to use PCW for few-shot for NQ it should be relatively similar to the existing code.
- If you wish to use PCW for retrieved documents (as done in the paper) - it will be easier to only use the model wrappers and not the entire classification suite (see example in the readme file).

You can find the prompts formats used for those cases in the paper, if you wish to add this functionality and commit the code here we will be happy to review it.
Feel free to ask if you have anymore questions.

**Comment by salvatoreferragamo** [comment]
thanks for reply! 
and i will try it according to your advise!
